[project]
name = "cheeew-detectino"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "opencv-python>=4.13.0.90",
    "ruff>=0.14.13",
]
